二項係数ライブラリの追加
kemuniku/cplib pull request #17
Opened 2023-11-03 19:09 UTC by kemuniku

未テスト

2023-11-03 20:25 UTC, seekworser requested changes

2023-11-03 20:25 UTC, seekworser commented on src/cplib/math/combination.nim
> +            return 0
```suggestion
        if n < 0 or r < 0 or n < r:
            return 0
```

2023-11-03 20:25 UTC, seekworser commented on src/cplib/math/combination.nim
> +        result.fact_inv = newSeq[ModInt](max_N+1)
```suggestion
        var fact = newSeq[ModInt](max_N+1)
        var inv = newSeq[ModInt](max_N+1)
        var fact_inv = newSeq[ModInt](max_N+1)
```

2023-11-03 20:44 UTC, seekworser approved these changes

2023-11-03 21:00 UTC, kemuniku commented
nprのテストも行いたいですね(nhrはncrが動作するならまぁいらないとは思っていますが)

2023-11-04 09:02 UTC, kemuniku commented
ok

2023-11-04 09:02 UTC, merged